### ISSUE TITLE
Unable to persist block chain data

### ISSUE THREAD

**Issue by grakshith** [pixelspark/catena#135]
The blockchain data does not seem to be stored in the .sqlite files, so when I restart catena, I lose all the data that has been previously a part of the blockchain.
Also, where is the data stored (I examined the sqlite files, but they didn't seem to store the data).

**Comment by grakshith** [comment]
Catena processes all the data, but it is never committed to the sqlite file. I can see that it rollbacks the transactions.

In that case, how do I run catena only on one node, and still get the consensus?

**Comment by pixelspark** [comment]
Hi,

Catena will buffer a certain number of blocks (and hence the transactions included in them) and not commit them to the database, as the tip of the chain may still be 'overtaken' by a better one (e.g. a chain head with a higher amount of work).

Because Catena still needs to expose the latest changes to its clients, it will (for each query) execute the buffered transactions, perform your query, then perform a rollback. While this obviously is costly in terms of performance (and as you noticed also prevents data from being flushed to disk), it is a trade-off against having to rewrite the full database (e.g. replaying *all* mutating queries on an empty database) whenever the head of the chain changes. Currently I believe the buffer has a size of 7 blocks, so when the 8th block is appended, the first should be committed to the database and be permanent.

**Comment by grakshith** [comment]
Thanks a lot!
